set(TOOLCHAIN_ROOT "${CMAKE_SOURCE_DIR}/toolchains/mingw64")

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER   "${TOOLCHAIN_ROOT}/bin/gcc.exe")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_ROOT}/bin/g++.exe")
set(CMAKE_RC_COMPILER  "${TOOLCHAIN_ROOT}/bin/windres.exe")

set(CMAKE_MAKE_PROGRAM "${CMAKE_SOURCE_DIR}/toolchains/ninja.exe")

set(CMAKE_FIND_ROOT_PATH "${TOOLCHAIN_ROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
